### PR TITLE
minor fix and update 

### PR DESCRIPTION
**Pull request by whatvn**
- Remove techOrder option when init player 
- call startLoad() instead of recoverNetworkError (which is unavailable)
- update videojs to 5.2.4

### CODE REVIEW

**Comment by whatvn** [comment]
@aronallen  plz take a look

**Comment by aronallen** [comment]
@whatvn thanks, I think we should just remove the peer dependency all together.

**Comment by codex-corp** [comment]
@whatvn 
https://github.com/whatvn/videojs-hlsjs/blob/master/lib/videojs-hlsjs.js#L19
Should be `MEDIA_ATTACHED` since it was deprecated in version 0.3.13 
check this commit https://github.com/dailymotion/hls.js/commit/7f641dff4d944d733185dc3c36aa301b8ac799c9

**Comment by codex-corp** [comment]
@whatvn 
https://github.com/whatvn/videojs-hlsjs/blob/master/lib/videojs-hlsjs.js#L73
Should be `BUFFER_APPENDING_ERROR`  since it was replaced in version 0.3.13 
check this commit https://github.com/dailymotion/hls.js/commit/b655ed8e3f120a8a506d7c049c9eaab9af48b05f

**Comment by whatvn** [comment]
@codex-corp you're right again, can you make that commit?

**Comment by aronallen** [comment]
@whatvn I already did, thanks for the commits!

**Pull request merged**
